import type { RegistryEntry, RegistryModel } from "../../shared.ts";
import { resolvePublicCred } from "../../shared.ts";

export const GEMINI_CLI_MODELS: readonly RegistryModel[] = Object.freeze([
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
  {
    id: "gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    contextLength: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsVision: true,
    supportsAudio: true,
    supportsVideo: true,
    toolCalling: true,
  },
]);

export const geminiCliProvider: RegistryEntry = {
  id: "gemini-cli",
  alias: "gemini_cli",
  format: "gemini-cli",
  executor: "gemini-cli",
  baseUrls: [
    "https://cloudcode-pa.googleapis.com/v1internal",
    "https://daily-cloudcode-pa.googleapis.com/v1internal",
    "https://daily-cloudcode-pa.sandbox.googleapis.com/v1internal",
  ],
  authType: "oauth",
  authHeader: "bearer",
  headers: {
    "User-Agent": "GeminiCLI/0.31.0 (win32; x64) google-api-nodejs-client/10.6.1",
    "X-Goog-Api-Client": "gl-node/22.17.1",
    Accept: "*/*",
    "Accept-Encoding": "gzip, deflate, br",
    Connection: "close",
  },
  oauth: {
    clientIdEnv: "GEMINI_CLI_OAUTH_CLIENT_ID",
    clientIdDefault: resolvePublicCred("gemini_id"),
    clientSecretEnv: "GEMINI_CLI_OAUTH_CLIENT_SECRET",
    clientSecretDefault: resolvePublicCred("gemini_alt"),
  },
  models: [...GEMINI_CLI_MODELS],
  passthroughModels: true,
  liveCatalogAuthoritative: false,
};

export const gemini_cliProvider = geminiCliProvider;
